name: Deploy React App 
on:
  push:
    branches:
        - master  
    #paths-ignore:
      #- '.github/workflows/*'
jobs:
  test-react-app: # Имя задания (может быть любым)
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Cache deps
        uses: actions/cache@v3
        with:
            path: ~/.npm
            key: node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Cache deps
        uses: actions/cache@v3
        with:
            path: ~/.npm
            key: node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [lint,test-react-app]
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Cache deps
        uses: actions/cache@v3
        with:
            path: ~/.npm
            key: node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...